version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    # ports:
    #   - "90:80"
    depends_on:
      - backend
  backend:
    build: .
    # ports:
    #   - "3000:3000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=namesdb
      - POSTGRES_HOST=db
    depends_on:
      - db

  backend1:
    build: .
    # ports:
    #   - "3001:3000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=namesdb
      - POSTGRES_HOST=db
    depends_on:
      - db
    
  backend2:
    build: .
    # ports:
    #   - "3002:3000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=namesdb
      - POSTGRES_HOST=db
    depends_on:
      - db


  db:
    image: postgres:14-alpine
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=namesdb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:latest
    ports:
      - "100:80"
    depends_on:
      - frontend
      - backend
      - backend1
      - backend2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf